# To create containers: docker-compose up -d
# To start previously created containers: docker compose start
# To stop containers: docker compose stop

version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-jdbc
    environment:
      MYSQL_ROOT_PASSWORD: qweqwe12
    networks:
      - jdbc-network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin-container-jdbc
    environment:
      PMA_HOST: mysql
    networks:
      - jdbc-network
    ports:
      - "8080:80"

networks:
  jdbc-network:
    driver: bridge

